15-12-2020
DaliaZhran/problem-solving pull request #1
Opened 2020-12-16 00:20 UTC by DaliaZhran

2020-12-16 12:05 UTC, EhabIbrahimH commented on 11. Container With Most Water.py
Check also https://leetcode.com/problems/trapping-rain-water/ with DP and 2 pointers approaches.

2020-12-16 12:21 UTC, EhabIbrahimH commented on 3Sum Smaller.py
This problem is more tricky at the interviews than when you see the solution, make sure you totally understand it and can code it without help

2020-12-16 13:32 UTC, EhabIbrahimH requested changes
Good job, waiting for more

2020-12-16 13:32 UTC, EhabIbrahimH commented on Multiply Strings.py
> +                result[temp_pos] += int(num1[i]) * int(num2[j])
This mustn't be used, resolve without any casting

2020-12-16 13:32 UTC, EhabIbrahimH commented on Rotate Image.py
> +            matrix[i] = reversed(matrix[i])
This is cool to mention that you new reversed built in function, but you must know how to do it optimally without built in functions

2020-12-16 13:32 UTC, EhabIbrahimH commented on Rotate Image.py
> +        for i in range(n / 2):
If you get problem like this, mention the reverse built in function and this one

2020-12-19 15:49 UTC, merged

2020-12-20 12:36 UTC, DaliaZhran commented on 11. Container With Most Water.py
done